### ISSUE TITLE
`download.sh` needs to be replaced with `install-powershell.sh` in 'setup.sh'

### ISSUE THREAD

**Issue by daxian-dbw** [nozzlegear/dotfiles#1]
I find the references to the powershell `download.sh` in [`setup.sh`](https://github.com/nozzlegear/dotfiles/blob/23b73eba7ba1dc483e7055c6aad88b0418cd51b8/setup.sh#L49) from a search in Github.

The `download.sh` file under the `tools` folder of the [PowerShell repository](https://github.com/PowerShell/PowerShell) was deprecated and now is removed. Please use the `install-powershell.sh` file from the same folder to install powershell on Linux.

**Comment by nozzlegear** [comment]
Thanks for the warning! I've replaced `download.sh` with `install-powershell.sh`.
